# Generated by Django 3.1.3 on 2020-11-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Signup', 'verbose_name_plural': 'Signups'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AlterField(
            model_name='signup',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Member to which to assign this signup', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='api.member'),
        ),
    ]
