# Generated by Django 3.2.4 on 2021-06-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210607_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='group_google_cal_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Group Google Calendar ID'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group to which to assign this signup', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='api.group'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='singlevisit',
            name='group',
            field=models.ForeignKey(help_text='Group to which the single visit is registered to', on_delete=django.db.models.deletion.CASCADE, related_name='single_visits', to='api.group'),
        ),
        migrations.AlterField(
            model_name='singlevisit',
            name='member',
            field=models.ForeignKey(help_text='Member to which the single visit is registered to', on_delete=django.db.models.deletion.CASCADE, related_name='single_visits', to='api.member'),
        ),
        migrations.AlterField(
            model_name='singlevisit',
            name='payment',
            field=models.ForeignKey(help_text='Payment to which the single visit is registered to', on_delete=django.db.models.deletion.CASCADE, related_name='single_visit', to='api.payment'),
        ),
    ]
