# Generated by Django 3.2.4 on 2021-06-11 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210610_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='date',
        ),
        migrations.AddField(
            model_name='signup',
            name='single_visit',
            field=models.ForeignKey(blank=True, help_text='Single visit to which this signup is assigned', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='api.singlevisit'),
        ),
        migrations.AddField(
            model_name='signup',
            name='subscription_visit',
            field=models.ForeignKey(blank=True, help_text='Subscription visit to which this signup is assigned', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='api.subscriptionvisit'),
        ),
    ]
