# Generated by Django 3.2.4 on 2021-06-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210611_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='google_cal_id',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
