# Generated by Django 3.1.2 on 2020-10-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('mobile_number', models.CharField(max_length=10, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('description', models.CharField(blank=True, default='description...', max_length=300, verbose_name='Description')),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='img/member_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('0', 'Cash'), ('1', 'Transfer'), ('2', 'Card')], max_length=2)),
                ('payment_paid', models.CharField(choices=[('0', 'Pending'), ('1', 'Paid')], max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, default='description...', max_length=300, verbose_name='Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('description', models.CharField(blank=True, default='description...', max_length=300, verbose_name='Description')),
                ('member', models.ForeignKey(help_text='Member to which this subscription is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.member')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.payment')),
                ('subscription_type', models.ForeignKey(help_text='Select a subscription type', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_type', to='api.subscriptiontype')),
            ],
        ),
        migrations.CreateModel(
            name='SingleVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('member', models.ForeignKey(help_text='Member to which this single visit is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='single_visits', to='api.member')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.payment')),
            ],
        ),
    ]
