# Generated by Django 3.1.2 on 2020-10-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Group Category',
                'verbose_name_plural': 'Group Categories',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('mobile_number', models.CharField(max_length=11, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='img/member_profiles')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('method', models.CharField(choices=[('0', 'Cash'), ('1', 'Transfer'), ('2', 'Card')], default='0', max_length=2)),
                ('paid', models.CharField(choices=[('0', 'Pending'), ('1', 'Paid')], default='1', max_length=2)),
                ('member', models.ForeignKey(help_text='Payments that member has made', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.member')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('member', models.ForeignKey(help_text='Subscriptions that the member has', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.payment')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('-registration_date',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('number_of_visits', models.PositiveIntegerField()),
                ('validity_in_days', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Subscription Category',
                'verbose_name_plural': 'Subscription Categories',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_visits', to='api.group')),
                ('subscription', models.ForeignKey(help_text='A visit based on a subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_visits', to='api.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Visit',
                'verbose_name_plural': 'subscription Visits',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.subscriptioncategory'),
        ),
        migrations.CreateModel(
            name='SingleVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group', models.ForeignKey(help_text='Single visits that the group has', on_delete=django.db.models.deletion.CASCADE, related_name='single_visits', to='api.group')),
                ('member', models.ForeignKey(help_text='Single visits that the member has made', on_delete=django.db.models.deletion.CASCADE, related_name='single_visits', to='api.member')),
                ('payment', models.ForeignKey(help_text='Group to which a single visit occured', on_delete=django.db.models.deletion.CASCADE, related_name='single_visit', to='api.payment')),
            ],
            options={
                'verbose_name': 'Single Visit',
                'verbose_name_plural': 'Single Visits',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.itemcategory')),
                ('member', models.ForeignKey(help_text='Item purchases that the member has made', on_delete=django.db.models.deletion.CASCADE, related_name='item_purchases', to='api.member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_purchases', to='api.payment')),
            ],
            options={
                'verbose_name': 'Item Purchase',
                'verbose_name_plural': 'Item Purchases',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.ForeignKey(help_text='Category of the group', on_delete=django.db.models.deletion.CASCADE, related_name='group', to='api.groupcategory'),
        ),
    ]
