# Generated by Django 3.1.2 on 2020-10-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('mobile_number', models.CharField(max_length=10, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('description', models.CharField(blank=True, default='description...', max_length=300, verbose_name='Description')),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='img/member_profiles')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('0', 'Cash'), ('1', 'Transfer'), ('2', 'Card')], max_length=2)),
                ('payment_paid', models.CharField(choices=[('0', 'Pending'), ('1', 'Paid')], max_length=2)),
                ('member', models.ForeignKey(help_text='Payments that member has made', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.member')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('-payment_date',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, default='description...', max_length=300, verbose_name='Description')),
                ('number_of_visits', models.PositiveIntegerField()),
                ('validity_in_days', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Subscription type',
                'verbose_name_plural': 'Subscription types',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.payment')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
            bases=('api.payment',),
        ),
        migrations.CreateModel(
            name='SingleVisit',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.payment')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Single visit',
                'verbose_name_plural': 'Single visits',
                'ordering': ('-date',),
            },
            bases=('api.payment',),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.payment')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='description...', max_length=300, verbose_name='Description')),
                ('subscription_type', models.ForeignKey(help_text='Select a subscription type', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_type', to='api.subscriptiontype')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('-registration_date',),
            },
            bases=('api.payment',),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subscription', models.ForeignKey(help_text='A visit based on a subscription', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.subscription')),
            ],
            options={
                'verbose_name': 'Subscription visit',
                'verbose_name_plural': 'subscription visits',
            },
        ),
    ]
