# Generated by Django 3.1.2 on 2020-10-25 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_type',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.subscriptiontype'),
            preserve_default=False,
        ),
    ]
