# Generated by Django 3.1.2 on 2020-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date',
            field=models.DateTimeField(default='2020-04-04 20:20'),
            preserve_default=False,
        ),
    ]
