# Generated by Django 3.1.2 on 2020-11-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0004_auto_20201103_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcategory',
            options={'ordering': ('name',), 'verbose_name': 'Group Category', 'verbose_name_plural': 'Group Categories'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
