# Generated by Django 3.1.2 on 2020-10-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ('price',), 'verbose_name': 'Item Category', 'verbose_name_plural': 'Item Categories'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='subscriptioncategory',
            options={'ordering': ('price',), 'verbose_name': 'Subscription Category', 'verbose_name_plural': 'Subscription Categories'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionvisit',
            options={'ordering': ('-date',), 'verbose_name': 'Subscription Visit', 'verbose_name_plural': 'subscription Visits'},
        ),
    ]
