# Generated by Django 3.1.2 on 2020-10-29 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date',), 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_paid',
            new_name='paid',
        ),
    ]
