# Generated by Django 3.1.2 on 2020-10-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscription_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type',
        ),
    ]
