# Generated by Django 3.1.2 on 2020-11-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201104_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlevisit',
            options={'ordering': ('-group__date',), 'verbose_name': 'Single Visit', 'verbose_name_plural': 'Single Visits'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionvisit',
            options={'ordering': ('-group__date',), 'verbose_name': 'Subscription Visit', 'verbose_name_plural': 'subscription Visits'},
        ),
        migrations.RemoveField(
            model_name='singlevisit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subscriptionvisit',
            name='date',
        ),
    ]
