# Generated by Django 3.1.2 on 2020-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201029_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('0', 'Cash'), ('1', 'Transfer'), ('2', 'Card')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Paid')], default='1', max_length=2),
        ),
    ]
