# Generated by Django 3.1.2 on 2020-10-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201029_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subscriptioncategory',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
