# Generated by Django 3.1.2 on 2020-10-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201029_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.BooleanField(default=True),
        ),
    ]
