# Generated by Django 3.1.2 on 2020-10-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201029_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(help_text='Category of the group', on_delete=django.db.models.deletion.CASCADE, related_name='group', to='api.groupcategory'),
        ),
        migrations.AlterField(
            model_name='singlevisit',
            name='group',
            field=models.ForeignKey(help_text='Single visits that the group has', on_delete=django.db.models.deletion.CASCADE, related_name='single_visits', to='api.group'),
        ),
        migrations.AlterField(
            model_name='singlevisit',
            name='payment',
            field=models.ForeignKey(help_text='Group to which a single visit occured', on_delete=django.db.models.deletion.CASCADE, related_name='single_visit', to='api.payment'),
        ),
        migrations.AlterField(
            model_name='subscriptionvisit',
            name='subscription',
            field=models.ForeignKey(help_text='A visit based on a subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_visits', to='api.subscription'),
        ),
    ]
