# Generated by Django 3.1.2 on 2020-11-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201104_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempurchase',
            name='date',
        ),
    ]
