# Generated by Django 3.1.2 on 2020-10-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_subscription_subscription_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='sub_type',
            new_name='subscription_type',
        ),
    ]
