# Generated by Django 3.1.2 on 2020-10-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='account',
        ),
        migrations.AddField(
            model_name='payment',
            name='write_off',
            field=models.BooleanField(default=False),
        ),
    ]
