# Generated by Django 3.1.2 on 2020-11-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_itempurchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_extensions', to='api.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Extension',
                'verbose_name_plural': 'Subscription Extensions',
                'ordering': ('-date',),
            },
        ),
    ]
