# Generated by Django 3.1.2 on 2020-10-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201029_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_type',
            new_name='subscription_category',
        ),
    ]
