# Generated by Django 3.1.3 on 2020-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subscriptionextension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Paid')], default='1', help_text='Payment status', max_length=2),
        ),
    ]
