# Generated by Django 3.1.3 on 2020-11-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201105_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False)),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('mobile_number', models.CharField(blank=True, max_length=11, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='Group')),
                ('member', models.ForeignKey(blank=True, help_text='Payments that member has made', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='api.member')),
            ],
            options={
                'verbose_name': 'Signup',
                'verbose_name_plural': 'Singups',
            },
        ),
    ]
