# Generated by Django 3.1.2 on 2020-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201029_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description'),
        ),
    ]
