# Generated by Django 3.1.2 on 2020-10-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201030_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'get_latest_by': 'date', 'ordering': ('-date',), 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='api_member_last_na_b4c4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['first_name'], name='first_name_idx'),
        ),
    ]
