# Generated by Django 3.1.2 on 2020-10-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201030_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(help_text='Category of the group', on_delete=django.db.models.deletion.CASCADE, related_name='group', to='api.groupcategory'),
        ),
        migrations.AlterField(
            model_name='itempurchase',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.itemcategory'),
        ),
        migrations.AlterField(
            model_name='itempurchase',
            name='member',
            field=models.ForeignKey(help_text='Item purchases that the member has made', on_delete=django.db.models.deletion.CASCADE, related_name='item_purchases', to='api.member'),
        ),
        migrations.AlterField(
            model_name='itempurchase',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_purchases', to='api.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(help_text='Payments that member has made', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.member'),
        ),
        migrations.AlterField(
            model_name='singlevisit',
            name='group',
            field=models.ForeignKey(help_text='Single visits that the group has', on_delete=django.db.models.deletion.CASCADE, related_name='single_visits', to='api.group'),
        ),
        migrations.AlterField(
            model_name='singlevisit',
            name='member',
            field=models.ForeignKey(help_text='Single visits that the member has made', on_delete=django.db.models.deletion.CASCADE, related_name='single_visits', to='api.member'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.payment'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.subscriptioncategory'),
        ),
        migrations.AlterField(
            model_name='subscriptionvisit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_visits', to='api.group'),
        ),
    ]
