# Generated by Django 3.1.2 on 2020-10-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_period',
        ),
    ]
