# Generated by Django 3.1.2 on 2020-10-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.ManyToManyField(related_name='type', to='app1.SubscriptionType'),
        ),
    ]
