# Generated by Django 3.1.2 on 2020-10-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201023_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.CreateModel(
            name='SingleVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=500, max_digits=10)),
                ('member', models.ForeignKey(help_text='Member to which this single visit is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='single_visits', to='app1.member')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.payment')),
            ],
        ),
    ]
