# Generated by Django 3.1.2 on 2020-10-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201023_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlevisit',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='price',
        ),
    ]
